/**
 * Xenon Base UI component inventory — the MVP reference set rendered on the
 * `/xenon` page. Each entry is rendered into a showcase card alongside a live
 * Base UI example (see `Gallery.tsx`).
 *
 * `render` selects the live example component for the card; primitives that
 * Base UI does not ship (textarea, table, badge, card surface) use semantic
 * HTML examples instead.
 */

export type ComponentCategory =
  | 'Form controls'
  | 'Overlays & navigation'
  | 'Data display & surfaces';

export interface ComponentDoc {
  id: string;
  name: string;
  primitive: 'base-ui' | 'semantic';
  source: string;
  category: ComponentCategory;
  purpose: string;
  anatomy: string[];
  variants: string[];
  states: string[];
  accessibility: string[];
  layout: string[];
  usage: string[];
  /** Key of the live example in `Gallery.tsx`. */
  render: string;
}

export const componentInventory: ComponentDoc[] = [
  {
    id: 'button',
    name: 'Button',
    primitive: 'base-ui',
    source: '@base-ui/react/button',
    category: 'Form controls',
    purpose: 'Triggers an action or event. The primary affordance for committing, submitting, or navigating.',
    anatomy: ['Label (text, required)', 'Optional leading/trailing icon', 'Focus ring on the control'],
    variants: ['Solid (primary action)', 'Secondary (bordered block)', 'Ghost (secondary)', 'Link (tertiary inline)'],
    states: ['Default', 'Hover', 'Focus-visible', 'Disabled', 'Loading'],
    accessibility: [
      'Renders a native <button>; keyboard and form semantics are free.',
      'Visible focus ring via :focus-visible.',
      'Disabled buttons are not focusable by default.',
      'Accessible name comes from the label or aria-label.',
    ],
    layout: ['Inline-flex, vertically centered', 'Gap between icon and label', 'Min tap target of 2.5rem'],
    usage: [
      'One primary button per surface; others become ghost or link.',
      'Never use a button for navigation that should be a link — use LinkButton.',
    ],
    render: 'button',
  },
  {
    id: 'text-field',
    name: 'Input / Text field',
    primitive: 'base-ui',
    source: '@base-ui/react/field + @base-ui/react/input',
    category: 'Form controls',
    purpose: 'Collects a single line of text. Paired with Field for label, hint, and error.',
    anatomy: ['Label (Field.Label)', 'Control input', 'Optional description / error message'],
    variants: ['Default', 'With description', 'With error', 'Disabled'],
    states: ['Empty', 'Focused', 'Filled', 'Error', 'Disabled'],
    accessibility: [
      'Label is associated to the input via the Field control.',
      'Description and error are wired to the input through Field',
      'Error text uses role="alert" semantics.',
    ],
    layout: ['Full width within its column', 'Consistent height with buttons', 'Border that shifts to accent on focus'],
    usage: [
      'Always pair with a visible label.',
      'Validate on blur or submit, never only on each keystroke.',
    ],
    render: 'text-field',
  },
  {
    id: 'textarea',
    name: 'Textarea',
    primitive: 'semantic',
    source: 'Field + native <textarea>',
    category: 'Form controls',
    purpose: 'Collects multi-line free text. Base UI has no dedicated textarea; use a semantic <textarea> inside Field.',
    anatomy: ['Label', 'Resizable <textarea>', 'Optional counter / description'],
    variants: ['Default', 'With character count', 'Error'],
    states: ['Empty', 'Focused', 'Filled', 'Error'],
    accessibility: [
      'Native <textarea> with an associated <label>.',
      'Rows attribute sets the visible height; resize is constrained vertically.',
    ],
    layout: ['Full width', 'Fixed min-height', 'Vertical-only resize to avoid breaking columns'],
    usage: ['Set rows to match expected content length.', 'Label above the field, never as placeholder-only.'],
    render: 'textarea',
  },
  {
    id: 'select',
    name: 'Select',
    primitive: 'base-ui',
    source: '@base-ui/react/select',
    category: 'Form controls',
    purpose: 'Chooses one value from a list in a popover listbox. Composable replacement for the native <select>.',
    anatomy: ['Trigger button', 'Selected value', 'Dropdown indicator', 'Popup listbox', 'Items'],
    variants: ['Single selection', 'Grouped items'],
    states: ['Closed', 'Open', 'Item highlighted', 'Disabled item', 'Disabled trigger'],
    accessibility: [
      'Trigger has aria-haspopup="listbox"; popup is a listbox role.',
      'Arrow, Home/End, and type-ahead navigation.',
      'Selected item is announced and reflected on the trigger.',
    ],
    layout: ['Trigger matches input height', 'Popup width tracks the trigger', 'Scrolls when the list is long'],
    usage: ['Use over radio groups when there are 5+ options.', 'Keep option labels short and parallel.'],
    render: 'select',
  },
  {
    id: 'checkbox',
    name: 'Checkbox',
    primitive: 'base-ui',
    source: '@base-ui/react/checkbox',
    category: 'Form controls',
    purpose: 'Toggles a single boolean or selects one item from a set of independent options.',
    anatomy: ['Box control', 'Indicator (check / dash)', 'Associated label'],
    variants: ['Checked', 'Unchecked', 'Indeterminate (group parent)'],
    states: ['Unchecked', 'Checked', 'Indeterminate', 'Hover', 'Focus', 'Disabled'],
    accessibility: [
      'Hidden native input keeps form and screen-reader semantics.',
      'Label is clickable and associated to the control.',
      'Indeterminate state is exposed for parent-of-group usage.',
    ],
    layout: ['Inline with its label', 'Aligned to the text baseline', 'Consistent control size across the form'],
    usage: ['Stack vertically for option lists.', 'Use indeterminate only for select-all group parents.'],
    render: 'checkbox',
  },
  {
    id: 'radio-group',
    name: 'Radio group',
    primitive: 'base-ui',
    source: '@base-ui/react/radio-group + @base-ui/react/radio',
    category: 'Form controls',
    purpose: 'Selects exactly one option from a mutually exclusive set.',
    anatomy: ['Group container (radiogroup role)', 'Radio controls', 'Labels', 'Optional group label'],
    variants: ['Stacked', 'Inline'],
    states: ['Unchecked', 'Selected', 'Focus', 'Disabled'],
    accessibility: [
      'Keyboard arrow keys move between options.',
      'Group exposes radiogroup role; each item is a radio.',
      'Selected option is reflected via aria-checked.',
    ],
    layout: ['Vertical stack by default', 'Even spacing between options', 'Group label sets the fieldset context'],
    usage: ['Use when all options should be visible (≤5).', 'For more options, switch to a Select.'],
    render: 'radio-group',
  },
  {
    id: 'switch',
    name: 'Switch',
    primitive: 'base-ui',
    source: '@base-ui/react/switch',
    category: 'Form controls',
    purpose: 'Toggles a setting that takes effect immediately (no submit needed).',
    anatomy: ['Track', 'Thumb', 'Associated label'],
    variants: ['On', 'Off'],
    states: ['Off', 'On', 'Hover', 'Focus', 'Disabled'],
    accessibility: [
      'Hidden native input preserves form submission.',
      'Switch exposes its on/off state to assistive tech.',
      'Always paired with a visible label.',
    ],
    layout: ['Inline label + control', 'Thumb animates between ends', 'Tap target ≥ 2.5rem'],
    usage: ['Use for instant settings, not form data that must be saved.', 'Prefer checkbox when a submit is required.'],
    render: 'switch',
  },
  {
    id: 'dialog',
    name: 'Dialog',
    primitive: 'base-ui',
    source: '@base-ui/react/dialog',
    category: 'Overlays & navigation',
    purpose: 'A modal surface that demands attention for a focused task or confirmation.',
    anatomy: ['Backdrop', 'Popup', 'Title', 'Description', 'Close affordance'],
    variants: ['Centered modal', 'Side sheet'],
    states: ['Closed', 'Opening', 'Open', 'Closing'],
    accessibility: [
      'Focus is trapped inside the popup while open.',
      'Escape closes; focus returns to the trigger.',
      'aria-labelledby / aria-describedby wire title and description.',
    ],
    layout: ['Centered with a max width', 'Backdrop dims and blocks the page', 'Scrolls internally if content overflows'],
    usage: ['Use sparingly — interruptive by design.', 'Always provide an explicit close control.'],
    render: 'dialog',
  },
  {
    id: 'popover',
    name: 'Popover',
    primitive: 'base-ui',
    source: '@base-ui/react/popover',
    category: 'Overlays & navigation',
    purpose: 'Non-modal floating content anchored to a trigger. For supplemental information or quick actions.',
    anatomy: ['Trigger', 'Positioner', 'Popup', 'Optional arrow', 'Title'],
    variants: ['Anchored', 'With arrow'],
    states: ['Closed', 'Open'],
    accessibility: [
      'Light dismiss: outside click or Escape closes.',
      'Popup role is dialog with a labelled title.',
      'Focus moves into the popup and returns on close.',
    ],
    layout: ['Anchored to the trigger', 'Flips to stay on screen', 'Constrained to the viewport'],
    usage: ['Prefer over a Dialog for non-interruptive detail.', 'Keep content brief and actionable.'],
    render: 'popover',
  },
  {
    id: 'tooltip',
    name: 'Tooltip',
    primitive: 'base-ui',
    source: '@base-ui/react/tooltip',
    category: 'Overlays & navigation',
    purpose: 'A short contextual label for a control. Supplements — never replaces — an accessible name.',
    anatomy: ['Trigger', 'Positioner', 'Popup', 'Optional arrow'],
    variants: ['Top', 'Right', 'Bottom', 'Left'],
    states: ['Closed', 'Open'],
    accessibility: [
      'Appears after a delay on hover and focus.',
      'Content must not be essential — tooltips can be hard to reach.',
      'Pair with a visible label or aria-label for the control.',
    ],
    layout: ['Anchored to the trigger', 'Auto-positions to stay on screen', 'Pointer-events disabled'],
    usage: ['Use for icons-only buttons.', 'Keep to one short line; never put interactive elements inside.'],
    render: 'tooltip',
  },
  {
    id: 'tabs',
    name: 'Tabs',
    primitive: 'base-ui',
    source: '@base-ui/react/tabs',
    category: 'Overlays & navigation',
    purpose: 'Switches between related sections of content within one surface.',
    anatomy: ['Tab list', 'Tabs', 'Active indicator', 'Tab panels'],
    variants: ['Horizontal', 'Vertical'],
    states: ['Inactive', 'Selected', 'Hover', 'Focus', 'Disabled'],
    accessibility: [
      'Tab role with roving tabindex; arrow keys move between tabs.',
      'Selected tab controls a labelled tabpanel.',
      'Only the selected panel is shown and announced.',
    ],
    layout: ['Tab list above its panels', 'Indicator underlines the active tab', 'Panels share the same region'],
    usage: ['Use to avoid long scrolling or multiple pages.', 'Order tabs by frequency or chronology.'],
    render: 'tabs',
  },
  {
    id: 'toast',
    name: 'Toast',
    primitive: 'base-ui',
    source: '@base-ui/react/toast',
    category: 'Overlays & navigation',
    purpose: 'Brief, transient confirmation of a background action. Non-blocking and auto-dismissed.',
    anatomy: ['Viewport', 'Toast root', 'Title', 'Description', 'Optional action', 'Close'],
    variants: ['Default', 'With action', 'High priority (urgent announce)'],
    states: ['Entering', 'Open', 'Exiting'],
    accessibility: [
      'Polite announcement by default; high priority announces urgently.',
      'Remains focusable and dismissable; Escape closes.',
      'Auto-dismisses after a timeout unless paused.',
    ],
    layout: ['Fixed to a viewport corner', 'Stacks newest on top', 'Pointer and swipe to dismiss'],
    usage: ['Triggered by an action the user just took.', 'Do not use for errors that require a decision — use a Dialog.'],
    render: 'toast',
  },
  {
    id: 'menu',
    name: 'Dropdown / Menu',
    primitive: 'base-ui',
    source: '@base-ui/react/menu',
    category: 'Overlays & navigation',
    purpose: 'A list of actions or choices revealed from a trigger. Contextual command palette.',
    anatomy: ['Trigger', 'Positioner', 'Popup (menu role)', 'Items', 'Optional group labels / separators'],
    variants: ['Action menu', 'Grouped menu'],
    states: ['Closed', 'Open', 'Item highlighted', 'Disabled item'],
    accessibility: [
      'Arrow keys navigate items; type-ahead jumps by label.',
      'Items are menuitem roles; disabled items are not selectable.',
      'Light-dismiss and Escape close the menu.',
    ],
    layout: ['Anchored to the trigger', 'Min and max width bounds', 'Scrolls for long lists'],
    usage: ['Group related actions with labels.', 'Place destructive actions last and visually separated.'],
    render: 'menu',
  },
  {
    id: 'scroll-area',
    name: 'Scroll area',
    primitive: 'base-ui',
    source: '@base-ui/react/scroll-area',
    category: 'Overlays & navigation',
    purpose: 'A styled, cross-browser scroll container with custom thumb controls.',
    anatomy: ['Root', 'Viewport', 'Scrollbar', 'Thumb', 'Corner'],
    variants: ['Vertical', 'Horizontal', 'Both'],
    states: ['Idle', 'Hover', 'Active (dragging)'],
    accessibility: [
      'Native scroll behavior and keyboard paging preserved.',
      'Custom thumb does not remove the underlying scroll semantics.',
    ],
    layout: ['Fixed height/width on the root', 'Thumb scales with content ratio', 'Content overflow is virtual-safe'],
    usage: ['Use where the native scrollbar clashes with the surface.', 'Always provide a clear height bound.'],
    render: 'scroll-area',
  },
  {
    id: 'card',
    name: 'Card',
    primitive: 'semantic',
    source: 'Semantic <article>',
    category: 'Data display & surfaces',
    purpose: 'A bounded surface that groups related content. The workhorse panel of a layout.',
    anatomy: ['Surface panel', 'Optional media', 'Header (title / meta)', 'Body', 'Optional footer'],
    variants: ['Flat', 'Bordered', 'Interactive (whole card is a link)'],
    states: ['Default', 'Hover (interactive)'],
    accessibility: [
      'Use a heading inside the card for its title.',
      'Interactive cards wrap content in a single link with an accessible name.',
    ],
    layout: ['Consistent radius and border', 'Padding follows the spacing scale', 'Media respects aspect ratio'],
    usage: ['One idea per card.', 'Keep interactive-card tap targets large.'],
    render: 'card',
  },
  {
    id: 'table',
    name: 'Table',
    primitive: 'semantic',
    source: 'Semantic <table>',
    category: 'Data display & surfaces',
    purpose: 'Aligns structured rows and columns of data for scanning and comparison.',
    anatomy: ['Caption', 'Header row', 'Body rows', 'Cells', 'Optional footer'],
    variants: ['Default', 'Striped', 'Dense'],
    states: ['Default', 'Row hover'],
    accessibility: [
      'Real <table> semantics; scope on header cells.',
      'Caption describes the table for screen readers.',
    ],
    layout: ['Bordered cells', 'Header row distinguished', 'Horizontally scrollable on small screens'],
    usage: ['Use when precise comparison matters.', 'Right-align numeric columns.'],
    render: 'table',
  },
  {
    id: 'badge',
    name: 'Badge',
    primitive: 'semantic',
    source: 'Semantic <span>',
    category: 'Data display & surfaces',
    purpose: 'A compact label for status, category, or count. Read-only, not interactive.',
    anatomy: ['Pill surface', 'Short label', 'Optional dot'],
    variants: ['Neutral', 'Accent', 'Outline'],
    states: ['Default'],
    accessibility: ['Conveyed as plain text; pair color with a word, never color alone.'],
    layout: ['Inline with adjacent text', 'Pill radius', 'Single short line'],
    usage: ['Use sparingly to mark state or category.', 'Keep labels to one or two words.'],
    render: 'badge',
  },
  {
    id: 'separator',
    name: 'Separator',
    primitive: 'base-ui',
    source: '@base-ui/react/separator',
    category: 'Data display & surfaces',
    purpose: 'A horizontal or vertical rule that divides related sections of content.',
    anatomy: ['A single rule element'],
    variants: ['Horizontal', 'Vertical'],
    states: ['Default'],
    accessibility: [
      'Exposes separator role with aria-orientation.',
      'Decorative separators are hidden from assistive tech.',
    ],
    layout: ['Full width when horizontal', 'Hairline weight', 'Color uses the line token'],
    usage: ['Separate, do not decorate.', 'Prefer whitespace where a rule would only add noise.'],
    render: 'separator',
  },
  {
    id: 'avatar',
    name: 'Avatar',
    primitive: 'base-ui',
    source: '@base-ui/react/avatar',
    category: 'Data display & surfaces',
    purpose: 'Represents a person or entity with an image and a text fallback.',
    anatomy: ['Root', 'Image', 'Fallback (initials / icon)'],
    variants: ['Image', 'Initials fallback'],
    states: ['Loading', 'Loaded', 'Error → fallback'],
    accessibility: [
      'Image carries a meaningful alt, or is decorative when paired with a name.',
      'Fallback is announced when the image cannot load.',
    ],
    layout: ['Fixed square bounds', 'Centered circular crop', 'Consistent sizes across a list'],
    usage: ['Always provide a fallback.', 'Size avatars consistently within a list.'],
    render: 'avatar',
  },
];

export const componentCategories: ComponentCategory[] = [
  'Form controls',
  'Overlays & navigation',
  'Data display & surfaces',
];
